FROM node:22-slim AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# Build specifically for the MCP
RUN npx nest build mcp-server 

FROM node:22-slim
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
# Copy the entire dist folder exactly as Nest built it (keeping apps and libs intact)
COPY --from=builder /app/dist ./dist
COPY package.json .
EXPOSE 5038

# Run the specific main.js file for the MCP server
CMD ["node", "dist/apps/mcp-server/main.js"]