# Stage 1: Build
FROM node:22 AS builder
WORKDIR /app/backend

# Increase Node heap for webpack-based Nest build.
ENV NODE_OPTIONS=--max-old-space-size=4096

COPY package.json package-lock.json* ./
RUN npm ci --no-audit --prefer-offline
COPY . .
RUN npm run build

# Stage 2: Server
FROM node:22-slim
WORKDIR /app/backend

RUN apt-get update \
    && apt-get install -y curl

COPY package.json package-lock.json* ./
RUN npm ci --include=dev --no-audit --prefer-offline

COPY . .

COPY --from=builder /app/backend/dist ./dist

EXPOSE 4000
HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=3 CMD curl -f http://localhost:4000/healthcheck || exit 1
CMD ["npm", "run", "start:no-migration"]
