# STAGE 1: Build the app
FROM node:22-slim AS builder 
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nest build api-server 

# STAGE 2: Run the app
FROM node:22-slim
WORKDIR /app

# The 'builder' name here MUST match the 'AS builder' name above
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY package.json .

EXPOSE 4000
CMD ["node", "dist/apps/api-server/main"]